name: Update Labels via GraphQL
description: Fast label updates using GraphQL mutation (1-2 seconds)
author: AgentX Team

inputs:
  issue_number:
    description: Issue number to update labels on
    required: true
  add_labels:
    description: Comma-separated labels to add (e.g., "orch:pm-done,status:ready")
    required: false
    default: ""
  remove_labels:
    description: Comma-separated labels to remove
    required: false
    default: ""
  github_token:
    description: GitHub token with write permissions
    required: true
    default: ${{ github.token }}

outputs:
  updated:
    description: Whether update was successful
    value: ${{ steps.update.outputs.updated }}

runs:
  using: composite
  steps:
    - name: Update Labels using GraphQL
      id: update
      uses: actions/github-script@v7
      env:
        ISSUE_NUMBER: ${{ inputs.issue_number }}
        ADD_LABELS: ${{ inputs.add_labels }}
        REMOVE_LABELS: ${{ inputs.remove_labels }}
      with:
        github-token: ${{ inputs.github_token }}
        script: |
          const issueNumber = parseInt(process.env.ISSUE_NUMBER);
          const addLabels = process.env.ADD_LABELS
            .split(',')
            .map(l => l.trim())
            .filter(l => l.length > 0);
          const removeLabels = process.env.REMOVE_LABELS
            .split(',')
            .map(l => l.trim())
            .filter(l => l.length > 0);
          
          console.log(`🔍 Updating labels on issue #${issueNumber}...`);
          console.log(`  Add: ${addLabels.join(', ') || 'none'}`);
          console.log(`  Remove: ${removeLabels.join(', ') || 'none'}`);
          
          try {
            // Get issue node ID and current labels
            const { data: issue } = await github.rest.issues.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issueNumber
            });
            
            // Get label IDs for additions
            const labelIds = [];
            if (addLabels.length > 0) {
              const labelQuery = `
                query($owner: String!, $repo: String!, $labels: [String!]!) {
                  repository(owner: $owner, name: $repo) {
                    labels(first: 100, query: "") {
                      nodes {
                        id
                        name
                      }
                    }
                  }
                }
              `;
              
              const { repository } = await github.graphql(labelQuery, {
                owner: context.repo.owner,
                repo: context.repo.repo,
                labels: addLabels
              });
              
              for (const labelName of addLabels) {
                const label = repository.labels.nodes.find(l => l.name === labelName);
                if (label) {
                  labelIds.push(label.id);
                } else {
                  console.warn(`⚠️ Label "${labelName}" not found, will create it`);
                }
              }
            }
            
            // Add labels using GraphQL
            if (labelIds.length > 0) {
              const addMutation = `
                mutation($labelableId: ID!, $labelIds: [ID!]!) {
                  addLabelsToLabelable(input: {
                    labelableId: $labelableId,
                    labelIds: $labelIds
                  }) {
                    labelable {
                      ... on Issue {
                        number
                        labels(first: 50) {
                          nodes { name }
                        }
                      }
                    }
                  }
                }
              `;
              
              await github.graphql(addMutation, {
                labelableId: issue.node_id,
                labelIds: labelIds
              });
              
              console.log(`✅ Added labels: ${addLabels.join(', ')}`);
            }
            
            // Create missing labels and add them via REST
            const missingLabels = addLabels.filter(name => 
              !labelIds.length || !issue.labels.some(l => l.name === name)
            );
            
            if (missingLabels.length > 0) {
              for (const labelName of missingLabels) {
                try {
                  await github.rest.issues.createLabel({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    name: labelName,
                    color: 'ededed',
                    description: `Auto-created label: ${labelName}`
                  });
                  console.log(`✅ Created label: ${labelName}`);
                } catch (err) {
                  if (err.status !== 422) throw err; // Ignore "already exists"
                }
              }
              
              // Add via REST API
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issueNumber,
                labels: missingLabels
              });
            }
            
            // Remove labels via REST (GraphQL removal requires label IDs)
            if (removeLabels.length > 0) {
              for (const labelName of removeLabels) {
                try {
                  await github.rest.issues.removeLabel({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    issue_number: issueNumber,
                    name: labelName
                  });
                  console.log(`✅ Removed label: ${labelName}`);
                } catch (err) {
                  if (err.status !== 404) throw err; // Ignore "not found"
                }
              }
            }
            
            core.setOutput('updated', 'true');
            console.log(`✅ Successfully updated labels on issue #${issueNumber}`);
            
          } catch (error) {
            console.error(`❌ Label update failed: ${error.message}`);
            core.setOutput('updated', 'false');
            throw error;
          }
