#!/usr/bin/env pwsh
<#
.SYNOPSIS
  Score every skill in the repository, rank them, and flag low scorers.

.DESCRIPTION
  Iterates over every SKILL.md under .github/skills, invokes
  scripts/score-skill.ps1 to compute a 0-100 quality score, and emits a
  ranked stocktake report.

.PARAMETER Threshold
  Minimum acceptable score. Skills below this are flagged. Default 70.

.PARAMETER OutFile
  Optional Markdown report path. Defaults to
  docs/artifacts/reviews/STOCKTAKE-<yyyy-MM-dd>.md when -WriteReport is set.

.PARAMETER WriteReport
  Persist a Markdown stocktake report.

.PARAMETER Json
  Emit JSON instead of human summary.

.EXAMPLE
  pwsh scripts/stocktake.ps1
  pwsh scripts/stocktake.ps1 -Threshold 70 -WriteReport
#>

#Requires -Version 7.0

[CmdletBinding()]
param(
  [ValidateRange(0, 100)][int]$Threshold = 70,
  [string]$OutFile = '',
  [switch]$WriteReport,
  [switch]$Json
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$ROOT = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path
$scoreScript = Join-Path $ROOT 'scripts/score-skill.ps1'
if (-not (Test-Path $scoreScript)) {
  Write-Error "score-skill.ps1 not found at $scoreScript"
  exit 1
}

$results = New-Object System.Collections.Generic.List[object]

$rubricJson = & pwsh -NoProfile -File $scoreScript -All -MinScore $Threshold -Json 2>$null | Out-String
$rubric = $rubricJson | ConvertFrom-Json -Depth 20
foreach ($r in @($rubric.skills)) {
  $results.Add([pscustomobject]@{
    name     = $r.name
    category = $r.category
    score    = $r.score
    tier     = $r.tier
    blockers = @($r.blockers)
    flagged  = ($r.score -lt $Threshold -or @($r.blockers).Count -gt 0)
    path     = $r.path
  }) | Out-Null
}

$sorted = @($results | Sort-Object -Property score)
$flagged = @($sorted | Where-Object { $_.flagged })
$total = $sorted.Count
$avg = if ($total -gt 0) { [math]::Round((($sorted | Measure-Object -Property score -Average).Average), 1) } else { 0 }

$summary = [pscustomobject]@{
  scanned_at = (Get-Date).ToUniversalTime().ToString('o')
  total      = $total
  average    = $avg
  threshold  = $Threshold
  flagged    = @($flagged)
  ranked     = @($sorted)
}

if ($Json) {
  Write-Output ($summary | ConvertTo-Json -Depth 6)
}
else {
  Write-Host ""
  Write-Host "AgentX skill stocktake" -ForegroundColor Cyan
  Write-Host ("Scanned: {0}   Average: {1}/100   Threshold: {2}   Flagged: {3}" -f $total, $avg, $Threshold, $flagged.Count)
  Write-Host ""
  if ($flagged.Count -gt 0) {
    Write-Host "Below threshold:" -ForegroundColor Yellow
    foreach ($item in $flagged) {
      Write-Host ("  [{0}/100] {1} ({2}) blockers={3} -> {4}" -f $item.score, $item.name, $item.category, ($item.blockers -join ','), $item.path) -ForegroundColor Yellow
    }
    Write-Host ""
  }
  Write-Host "Top 5:"
  foreach ($item in ($sorted | Sort-Object -Property score -Descending | Select-Object -First 5)) {
    Write-Host ("  [{0}/100] {1} ({2})" -f $item.score, $item.name, $item.category) -ForegroundColor Green
  }
  Write-Host ""
}

if ($WriteReport) {
  $date = (Get-Date).ToString('yyyy-MM-dd')
  if (-not $OutFile) {
    $reviewsDir = Join-Path $ROOT 'docs/artifacts/reviews'
    New-Item -ItemType Directory -Force -Path $reviewsDir | Out-Null
    $OutFile = Join-Path $reviewsDir "STOCKTAKE-$date.md"
  }
  $md = @()
  $md += "# Skill Stocktake -- $date"
  $md += ""
  $md += "Scanned **$total** skills. Average score **$avg/100**. Threshold **$Threshold**. Flagged **$($flagged.Count)**."
  $md += ""
  if ($flagged.Count -gt 0) {
    $md += "## Below Threshold"
    $md += ""
    $md += "| Score | Skill | Category | Path |"
    $md += "|-------|-------|----------|------|"
    foreach ($item in $flagged) {
      $md += "| $($item.score)/100 | $($item.name) | $($item.category) | $($item.path) |"
    }
    $md += ""
  }
  $md += "## Full Ranking (lowest first)"
  $md += ""
  $md += "| Score | Tier | Skill | Category |"
  $md += "|-------|------|-------|----------|"
  foreach ($item in $sorted) {
    $md += "| $($item.score)/100 | $($item.tier) | $($item.name) | $($item.category) |"
  }
  $md += ""
  $md += "_Generated by_ `scripts/stocktake.ps1`."
  Set-Content -Path $OutFile -Value ($md -join "`r`n") -Encoding utf8
  Write-Host "Report written: $OutFile"
}

if ($flagged.Count -gt 0) { exit 1 }
exit 0

